### ISSUE TITLE
Different F1 score value

### ISSUE THREAD

**Issue by wesamalnabki** [tavo91/NER-WNUT17#1]
Hello

I tried to reproduce the results. So, I downloaded the code and the required embedding model. However, when I run the  wnuteval code, I get a lower F1 score, but when I run the evaluation script on your submission file I get the claimed F1 score (41.86%)

Here is the evaluation for the crfsuit.tsv output:

### ENTITY F1-SCORES ###
processed 23394 tokens with 1740 phrases; 
found: 846 phrases; correct: 480.

accuracy:  93.77%; 
precision:  56.74%; 
recall:  27.59%; 
**FB1:  37.12**

      corporation: 
precision:  20.51%; 
recall:   9.09%; 
FB1:  12.60  8

    creative-work: 
precision:  22.86%; 
recall:   2.22%; 
FB1:   4.05  8

            group: 
precision:  38.36%; 
recall:  11.91%; 
FB1:  18.18  28

         location: 
precision:  44.30%; 
recall:  41.39%; 
FB1:  42.80  101

           person: 
precision:  77.13%; 
recall:  50.00%; 
FB1:  60.67  280

          product: 
precision:  50.93%; 
recall:  21.74%; 
FB1:  30.47  55

### SURFACE FORM F1-SCORES ###
processed 23394 tokens with 1382 phrases; 
found: 700 phrases; correct: 387.

accuracy:  93.77%; 
precision:  55.29%; 
recall:  28.00%; 
FB1:  37.18

      corporation: 
precision:  21.62%; 
recall:  10.26%; 
FB1:  13.91  8

    creative-work: 
precision:  25.00%; 
recall:   2.83%; 
FB1:   5.08  8

            group: 
precision:  36.67%; 
recall:  11.89%; 
FB1:  17.96  22

         location: 
precision:  40.96%; 
recall:  45.29%; 
FB1:  43.02  77

           person: 
precision:  77.67%; 
recall:  49.68%; 
FB1:  60.60  233

          product: 
precision:  46.99%; 
recall:  19.80%; 
FB1:  27.86  39

**Comment by gaguilar** [comment]
Hi @Wesam266 

Thank you for reaching out and sorry for the problems this could have caused you.

I left wrong default parameters in some of the network functions when I organized the code (i.e., number of epochs and batch size). I have corrected those and generated predictions from there, you can check them in the predictions file running the `./eval.sh` script. 

Additionally, I have added the notebook I used when I developed this system. I think it will be better to use the notebook for reproducibility since it is easier to keep track of the pipeline. 

Finally, you may not get the exact same results reported in the paper as there are many places that use randomness. I'll try to make this deterministic anytime soon.
